Failures:
  1) Linked Prueba de las partes fundamentales de la clase Linked: Pueba de los metodos secundarios de la clase Linked: Extrael primer elemento
     Failure/Error: lista.ex_1er_elemento()

     NoMethodError:
       undefined method `ex_1er_elemento' for #<Linked:0x00000001be4f78>
     # ./spec/prct6_spec.rb:59:in `block (4 levels) in <top (required)>'