Failures:
  1) Linked ->Comprobar si esta vacío
     Failure/Error: expect(@lista_L.empty?).to eq(false)

       expected: false
            got: true

       (compared using ==)
     # ./spec/prct6_spec.rb:78:in `block (2 levels) in <top (required)>'

  2) Linked -> El head de la lista_L no puede estar a nil si hay elementos en la lista
     Failure/Error: expect(@lista_L.head.value).not_to be_nil

     NoMethodError:
       undefined method `value' for nil:NilClass
     # ./spec/prct6_spec.rb:82:in `block (2 levels) in <top (required)>'

Finished in 0.03392 seconds (files took 0.16648 seconds to load)
11 examples, 2 failures