Failures:
  1) MenuDSL Prueba de las partes fundamentales de la clase Dieta: -> Dieta Almuerzo
     Failure/Error: expect(@almuerzo.titulo).to eq("Almuerzo")

     NoMethodError:
       undefined method `titulo' for #<MenuDSL:0x0000000240b440>
     # ./spec/prct6_spec.rb:23:in `block (3 levels) in <top (required)>'

Finished in 0.00534 seconds (files took 0.19736 seconds to load)
3 examples, 1 failure