1) Dieta Prueba de las partes fundamentales de la clase Dieta: -> El V.C.T del objeto2 es igual al objeto3 pero los porcentajes no son iguales      Failure/Error: expect(objeto2 == objeto3).to eq(false)
     NameError:
       undefined local variable or method `objeto3' for #<RSpec::ExampleGroups::Dieta::PruebaDeLasPartesFundamentalesDeLaClaseDieta:0x000000011d8b88>
       Did you mean?  object_id
     # ./spec/prct6_spec.rb:66:in `block (3 levels) in <top (required)>'

Finished in 0.01755 seconds (files took 0.13964 seconds to load)
40 examples, 1 failure