Failures:
  1) MenuDSL Prueba de las partes fundamentales de la clase Dieta: -> Dieta Almuerzo
     Failure/Error: expect(@almuerzo.ingesta).to eq([[30, 35]])

     NoMethodError:
       undefined method `ingesta' for #<MenuDSL:0x00000002716310 @nombre="Ejemplo", @titulo="Almuerzo">
     # ./spec/prct6_spec.rb:27:in `block (3 levels) in <top (required)>'

Finished in 0.00696 seconds (files took 0.12807 seconds to load)
4 examples, 1 failure