Failures:
  1) Linked -> El head de la lista_M no puede estar a nil si hay elementos en la lista
     Failure/Error: expect(@lista_M.head.value).not_to be_nil

     NoMethodError:
       undefined method `value' for nil:NilClass
     # ./spec/prct6_spec.rb:146:in `block (2 levels) in <top (required)>'

Finished in 0.00663 seconds (files took 0.15002 seconds to load)
13 examples, 1 failure