Failures:
  1) Linked -> Dieta Lunes
     Failure/Error: @nomb=@aux.value[0][0]

     NoMethodError:
       undefined method `[]' for #<MenuDSL:0x0000000150da88>
     # ./lib/prct6/linked.rb:39:in `to_s'
     # ./spec/prct6_spec.rb:142:in `block (2 levels) in <top (required)>'

Finished in 0.00752 seconds (files took 0.12719 seconds to load)
12 examples, 1 failure