1) Linked Prueba de que la lista se crea a vacía ->el menor V.C.T de los elementos de la lista      Failure/Error: expect(lista.min).to eq(255.5)
     NoMethodError:
       undefined method `min' for #<Linked:0x0000000206a480>
     # ./spec/prct6_spec.rb:100:in `block (3 levels) in <top (required)>'

  2) Linked Prueba de que la lista se crea a vacía ->el mayor V.C.T de los elementos de la lista
     Failure/Error: expect(lista.max).to eq(785.9)

     NoMethodError:
       undefined method `max' for #<Linked:0x0000000206a480>
     # ./spec/prct6_spec.rb:104:in `block (3 levels) in <top (required)>'

Finished in 0.0127 seconds (files took 0.13604 seconds to load)
38 examples, 2 failures