Failures:
  1) MenuDSL Prueba de las partes fundamentales de la clase Dieta: -> Dieta Almuerzo
     Failure/Error: expect(@almuerzo.platos).to eq([["Macarrones con salsa de tomate y queso parmesano","1 1/2 cucharón","200"],["Escalope de ternera","1 bistec mediano","100"],["Ensalada básica con zanahoria rallada","guarnición","120"],["Mandarina","1 grande","180"],["Pan de trigo integral","1 rodaja","20"]])

     NoMethodError:
       undefined method `platos' for #<MenuDSL:0x0000000120af20>
     # ./spec/prct6_spec.rb:32:in `block (3 levels) in <top (required)>'

Finished in 0.04928 seconds (files took 0.23695 seconds to load)
5 examples, 1 failure