Failures:
  1) Linked Prueba de las partes fundamentales de la clase Linked: Pueba de los metodos secundarios de la clase Linked: ->Comprobar si esta vacío
     Failure/Error: expect(lista.empty?).to eq(false)

     NoMethodError:
       undefined method `empty?' for #<Linked:0x000000020ed2e0>
     # ./spec/prct6_spec.rb:64:in `block (4 levels) in <top (required)>'